name: CI/CD Docker Image Build

on:
  push:
    branches: [ main ] # Запускать при пуше в ветку main

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Выполнять на чистой машине Ubuntu
    steps:
    - name: Checkout code # 1. Получить наш код из репозитория
      uses: actions/checkout@v4

    - name: Set up Docker Buildx # 2. Настроить инструменты для сборки Docker
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub # 3. Авторизоваться в Docker Hub (используя секреты!)
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image # 4. Собрать и отправить образ
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: myroslove/my-website:latest # Заменить
    - name: Deploy to Server (CD)
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: user        # Твой логин в Linux, если он другой - замени
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # 1. Загружаем свежий образ с Docker Hub
          docker pull myroslove/my-website:latest

          # 2. Удаляем старый контейнер (если он запущен)
          docker rm -f my-website || true

          # 3. Запускаем новый контейнер
          docker run -d \
            -p 8081:80 \
            --name my-website \
            --restart always \
            myroslove/my-website:latest!
