name: CI/CD Docker Image Build

on:
  push:
    branches: [ main ] # Запускать при пуше в ветку main

jobs:
  build-and-push:
    runs-on: self-hosted # Выполнять на M
    steps:
    - name: Checkout code # 1. Получить наш код из репозитория
      uses: actions/checkout@v4

    - name: Set up Docker Buildx # 2. Настроить инструменты для сборки Docker
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker # <--- Добавляем эту строчку

    - name: Log in to Docker Hub # 3. Авторизоваться в Docker Hub (используя секреты!)
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Запускаем Docker Buildx (Инициализация)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 2. Логинимся
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Сборка и Пуш
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: myroslove/my-website:latest # Заменить!
